name: example
description: Example app for animated_vector
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_vector:
    git:
      url: https://github.com/HrX03/animated_vector
      path: packages/animated_vector
  animated_vector_annotations:
    git:
      url: https://github.com/HrX03/animated_vector
      path: packages/animated_vector_annotations

  flutter:
    sdk: flutter

dev_dependencies:
  animated_vector_gen:
    git:
      url: https://github.com/HrX03/animated_vector
      path: packages/animated_vector_gen
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  lint: ^2.0.2

flutter:
  uses-material-design: true
