name: animated_vector
description: A package that adds support for vector data based animations.
version: 0.1.0
homepage: https://github.com/PotatoProject/animated_vector
license: MIT

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  
  path_parsing: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  lint: ^2.1.2

flutter: