name: animated_vector_annotations
description: Code generation annotations for animated_vector_gen and animated_vector.
version: 0.2.1
license: MIT
homepage: https://github.com/HrX03/animated_vector/tree/main/packages/animated_vector_annotations
repository: https://github.com/HrX03/animated_vector

environment:
  sdk: ^3.1.0

dependencies:
  animated_vector: ^0.2.1
  flutter:
    sdk: flutter
  meta: ^1.9.1
