name: animated_vector_gen
description: Generators for animated_vector
version: 0.1.0
license: MIT
homepage: https://github.com/HrX03/animated_vector/tree/main/packages/animated_vector_annotations
repository: https://github.com/HrX03/animated_vector

environment:
  sdk: ^3.1.0

dependencies:
  analyzer: ^6.2.0
  animated_vector_annotations: ^0.1.0
  build: ^2.4.1
  code_builder: ^4.7.0
  dart_style: ^2.3.3
  glob: ^2.1.2
  source_gen: ^1.4.0
