name: animated_vector_gen
description: "Generators for animated_vector"
version: 0.0.1

environment:
  sdk: ^3.1.0

dependencies:
  analyzer: ^6.2.0
  animated_vector_annotations:
    git:
      url: https://github.com/HrX03/animated_vector
      path: packages/animated_vector_annotations
  build: ^2.4.1
  code_builder: ^4.7.0
  dart_style: ^2.3.3
  glob: ^2.1.2
  source_gen: ^1.4.0
